[tool.ruff]
line-length = 100
target-version = "py311"
src = [
    "scripts",
]
extend-exclude = [
    "notebooks/**",
    "data/**",
    "logs/**",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # import order
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "PL",  # pylint rules (subset)
    "RUF", # ruff-specific rules
]
ignore = [
    "E501", # line length handled by formatter / notebooks often wider
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

