name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbformat ruff

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff . || true

      - name: Build Docker image (smoke)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: datasens:ci


